//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PELICULAS_WW
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_peliculas
    {
        public int IdPelicula { get; set; }
        public string Estreno { get; set; }
        public string Titulo { get; set; }
        public string Director { get; set; }
        public int Taquilla { get; set; }
        public string Genero { get; set; }
        public string Protagonistas { get; set; }
        public string Compañia { get; set; }
    }
}
